name = "MirrorDescent"
uuid = "e905d4db-6995-442a-90fc-5a160a9e6d8e"
authors = ["Julien Ugon <julien.ugon@deakin.edu.au>"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
